In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('eng_-french.csv')

In [3]:
df.head()

  English words/sentences French words/sentences
0                     Hi.                 Salut!
1                    Run!                Cours !
2                    Run!               Courez !
3                    Who?                  Qui ?
4                    Wow!             Ça alors !

In [4]:
df.tail()

,English words/sentences,French words/sentences
175616,"Top-down economics never works, said Obama. ""T...","« L'économie en partant du haut vers le bas, ç..."
175617,A carbon footprint is the amount of carbon dio...,Une empreinte carbone est la somme de pollutio...
175618,Death is something that we're often discourage...,La mort est une chose qu'on nous décourage sou...
175619,Since there are usually multiple websites on a...,Puisqu'il y a de multiples sites web sur chaqu...
175620,If someone who doesn't know your background sa...,Si quelqu'un qui ne connaît pas vos antécédent...

In [5]:
df.tail()['French words/sentences'].tolist()[0]

"« L'économie en partant du haut vers le bas, ça ne marche jamais, » a dit Obama. « Le pays ne réussit pas lorsque seulement ceux qui sont au sommet s'en sortent bien. Nous réussissons lorsque la classe moyenne s'élargit, lorsqu'elle se sent davantage en sécurité. »"

In [6]:
df = df.replace({
    "\u202f": " ",
    "\xa0": " ",
    "\ufeff": "",
    "\u200b": "",
}, regex=True)

In [7]:
df.head()

  English words/sentences French words/sentences
0                     Hi.                 Salut!
1                    Run!                Cours !
2                    Run!               Courez !
3                    Who?                  Qui ?
4                    Wow!             Ça alors !

In [8]:
df.tail()

,English words/sentences,French words/sentences
175616,"Top-down economics never works, said Obama. ""T...","« L'économie en partant du haut vers le bas, ç..."
175617,A carbon footprint is the amount of carbon dio...,Une empreinte carbone est la somme de pollutio...
175618,Death is something that we're often discourage...,La mort est une chose qu'on nous décourage sou...
175619,Since there are usually multiple websites on a...,Puisqu'il y a de multiples sites web sur chaqu...
175620,If someone who doesn't know your background sa...,Si quelqu'un qui ne connaît pas vos antécédent...

In [9]:
len(df)

175621

In [10]:
import torch
device = 'mps' if torch.mps.is_available() else ('cuda' if torch.cuda.is_available() else 'cpu')
device

'mps'

In [11]:
from torch.utils.data import DataLoader, Dataset
class FRDataset(Dataset):
    def __init__(self, df):
        super().__init__()
        self.df = df


    def __len__(self):
        return len(self.df)
    def __getitem__(self, idx):
        x, y = self.df.iloc[idx]
        return x, y

dataset = FRDataset(df)
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

In [12]:
#next(iter(dataloader))

In [71]:
import nltk
#nltk.download("punkt_tab")

from nltk.tokenize import word_tokenize

a, b = df.iloc[0]
print(a, b, type(a), type(b))
print(word_tokenize(a))
print(word_tokenize(b, language='french'))

Hi. Salut! <class 'str'> <class 'str'>
['Hi', '.']
['Salut', '!']

In [72]:
#vocab_en = (((''.join(df['English words/sentences'].iloc[:]))))
#vocab_fr = (((''.join(df['French words/sentences'].iloc[:]))))

#vocab_en = vocab_en.replace('.', '. ')
#vocab_en = vocab_en.replace('\\'+ '\'', '\'')

#vocab_fr = vocab_fr.replace('.', '. ')
#vocab_fr = vocab_fr.replace('\\' + '\'', '\'')

#vocab_en = word_tokenize(vocab_en, language='english')
#vocab_fr = word_tokenize(vocab_fr, language='french')